-- MySQL Script generated by MySQL Workbench
-- Sat Apr 12 14:21:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema casaapuestas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema casaapuestas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `casaapuestas` DEFAULT CHARACTER SET utf8 ;
USE `casaapuestas` ;

-- -----------------------------------------------------
-- Table `casaapuestas`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casaapuestas`.`Usuarios` (
  `telefono_usuario` CHAR(15) NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `correo` VARCHAR(100) NULL,
  `saldo` FLOAT NULL,
  `contrasena` VARCHAR(50) NULL,
  PRIMARY KEY (`telefono_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casaapuestas`.`Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casaapuestas`.`Eventos` (
  `id_Evento` INT NOT NULL AUTO_INCREMENT,
  `nombre_evento` VARCHAR(100) NULL,
  `fecha_evento` DATE NULL,
  PRIMARY KEY (`id_Evento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casaapuestas`.`Apuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casaapuestas`.`Apuestas` (
  `id_apuesta` INT NOT NULL,
  `fecha` DATE NULL,
  `monto` FLOAT NULL,
  `resultado` VARCHAR(30) NULL,
  `ganancia` FLOAT NULL,
  `id_Evento` INT NOT NULL,
  `telefono_usuario` CHAR(15) NOT NULL,
  PRIMARY KEY (`id_apuesta`),
  INDEX `fk_Apuesta_Evento1_idx` (`id_Evento` ASC) VISIBLE,
  INDEX `fk_Apuestas_Usuarios1_idx` (`telefono_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Apuesta_Evento1`
    FOREIGN KEY (`id_Evento`)
    REFERENCES `casaapuestas`.`Eventos` (`id_Evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apuestas_Usuarios1`
    FOREIGN KEY (`telefono_usuario`)
    REFERENCES `casaapuestas`.`Usuarios` (`telefono_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casaapuestas`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casaapuestas`.`Cargo` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `nombre_cargo` VARCHAR(50) NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casaapuestas`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casaapuestas`.`Empleados` (
  `telefono_empleado` CHAR(15) NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `correo` VARCHAR(100) NULL,
  `contrasena` VARCHAR(50) NULL,
  `id_cargo` INT NOT NULL,
  PRIMARY KEY (`telefono_empleado`),
  INDEX `fk_Empleados_Cargo1_idx` (`id_cargo` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_Cargo1`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `casaapuestas`.`Cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casaapuestas`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casaapuestas`.`Ventas` (
  `id_venta` INT NOT NULL,
  `fecha` DATE NULL,
  `importe` FLOAT NULL,
  `medio_pago` VARCHAR(50) NULL,
  `iva` FLOAT NULL,
  `total` FLOAT NULL,
  `telefono_empleado` CHAR(15) NOT NULL,
  `telefono_usuario` CHAR(15) NOT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_Ventas_Empleados1_idx` (`telefono_empleado` ASC) VISIBLE,
  INDEX `fk_Ventas_Usuarios1_idx` (`telefono_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Empleados1`
    FOREIGN KEY (`telefono_empleado`)
    REFERENCES `casaapuestas`.`Empleados` (`telefono_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Usuarios1`
    FOREIGN KEY (`telefono_usuario`)
    REFERENCES `casaapuestas`.`Usuarios` (`telefono_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casaapuestas`.`HistorialDePagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casaapuestas`.`HistorialDePagos` (
  `id_pago` INT NOT NULL,
  `tipo_pago` VARCHAR(50) NULL,
  `monto_pago` FLOAT NULL,
  `fecha_pago` DATE NULL,
  `telefono_usuario` CHAR(15) NOT NULL,
  PRIMARY KEY (`id_pago`),
  INDEX `fk_HistorialDePagos_Usuarios1_idx` (`telefono_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_HistorialDePagos_Usuarios1`
    FOREIGN KEY (`telefono_usuario`)
    REFERENCES `casaapuestas`.`Usuarios` (`telefono_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casaapuestas`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casaapuestas`.`Categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(50) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casaapuestas`.`Articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casaapuestas`.`Articulos` (
  `codigo` CHAR(13) NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `descripcion` VARCHAR(255) NULL,
  `precio` FLOAT NULL,
  `stock` INT NULL,
  `costo` FLOAT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_Articulos_Categoria1_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_Articulos_Categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `casaapuestas`.`Categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casaapuestas`.`Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casaapuestas`.`Detalle` (
  `id_venta` INT NOT NULL,
  `codigo` CHAR(13) NOT NULL,
  `id_Detalle` VARCHAR(45) NOT NULL,
  `cantidad` INT NULL,
  `precio` FLOAT NULL,
  `importe` FLOAT NULL,
  PRIMARY KEY (`id_Detalle`, `id_venta`, `codigo`),
  INDEX `fk_PuntoDeVenta_has_Productos_Productos1_idx` (`codigo` ASC) VISIBLE,
  INDEX `fk_PuntoDeVenta_has_Productos_PuntoDeVenta1_idx` (`id_venta` ASC) VISIBLE,
  CONSTRAINT `fk_PuntoDeVenta_has_Productos_PuntoDeVenta1`
    FOREIGN KEY (`id_venta`)
    REFERENCES `casaapuestas`.`Ventas` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PuntoDeVenta_has_Productos_Productos1`
    FOREIGN KEY (`codigo`)
    REFERENCES `casaapuestas`.`Articulos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
